"""Deterministic, third-party-payload-free calibrated multiview fixture."""

from __future__ import annotations

import hashlib
import os
import shutil
import struct
import tempfile
import zlib
from pathlib import Path
from typing import Any

from p2g.canonical import sha256_json, write_new_json
from p2g.errors import ContractError, OutputExistsError
from p2g.schema import validate_payload

FIXTURE_SCHEMA = "p2g.synthetic_multiview_fixture.v1"
GENERATOR_ID = "integer_rgb_pinhole_v1"
PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"


def _positive(name: str, value: int, *, minimum: int) -> int:
    if value < minimum:
        raise ContractError(f"{name} must be at least {minimum}")
    return value


def _png_chunk(kind: bytes, payload: bytes) -> bytes:
    checksum = zlib.crc32(kind)
    checksum = zlib.crc32(payload, checksum)
    return (
        struct.pack(">I", len(payload))
        + kind
        + payload
        + struct.pack(">I", checksum & 0xFFFFFFFF)
    )


def _stored_zlib_stream(payload: bytes) -> bytes:
    """Encode a zlib stream with explicit RFC 1951 stored blocks.

    Avoiding ``zlib.compress`` makes the PNG bytes independent of compressor
    heuristics and zlib-library versions.  The header declares the fastest
    algorithm, every block boundary is fixed, and the Adler-32 trailer is
    encoded explicitly.
    """

    blocks = bytearray(b"\x78\x01")
    offsets = range(0, len(payload), 65_535) if payload else (0,)
    for offset in offsets:
        block = payload[offset : offset + 65_535]
        final = offset + len(block) == len(payload)
        blocks.append(1 if final else 0)
        blocks.extend(struct.pack("<HH", len(block), len(block) ^ 0xFFFF))
        blocks.extend(block)
    blocks.extend(struct.pack(">I", zlib.adler32(payload) & 0xFFFFFFFF))
    return bytes(blocks)


def _rgb_payload(
    *,
    width: int,
    height: int,
    camera_index: int,
    frame_index: int,
) -> bytes:
    pixels = bytearray()
    moving_x = width // 2 + frame_index * 2 - camera_index
    moving_y = height // 2 + (frame_index % 2)
    radius = max(2, min(width, height) // 7)
    for y in range(height):
        for x in range(width):
            checker = 18 if ((x // 4) + (y // 4)) % 2 else 0
            red = 24 + (x * 139) // max(width - 1, 1) + checker
            green = 20 + (y * 123) // max(height - 1, 1) + camera_index * 7
            blue = 30 + frame_index * 13 + checker
            if (x - moving_x) ** 2 + (y - moving_y) ** 2 <= radius**2:
                red, green, blue = 240, 80 + frame_index * 12, 40 + camera_index * 15
            pixels.extend((min(red, 255), min(green, 255), min(blue, 255)))
    return bytes(pixels)


def _png_bytes(
    *,
    width: int,
    height: int,
    camera_index: int,
    frame_index: int,
) -> bytes:
    rgb = _rgb_payload(
        width=width,
        height=height,
        camera_index=camera_index,
        frame_index=frame_index,
    )
    stride = width * 3
    scanlines = b"".join(
        b"\x00" + rgb[offset : offset + stride]
        for offset in range(0, len(rgb), stride)
    )
    header = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    return (
        PNG_SIGNATURE
        + _png_chunk(b"IHDR", header)
        + _png_chunk(b"IDAT", _stored_zlib_stream(scanlines))
        + _png_chunk(b"IEND", b"")
    )


def _camera(camera_index: int, *, camera_count: int, width: int, height: int) -> dict[str, Any]:
    center_x = (camera_index - (camera_count - 1) / 2.0) * 0.12
    focal = float(max(width, height))
    return {
        "model": "pinhole",
        "pixel_domain": "undistorted",
        "intrinsic": [
            [focal, 0.0, width / 2.0],
            [0.0, focal, height / 2.0],
            [0.0, 0.0, 1.0],
        ],
        "world_to_camera": [
            [1.0, 0.0, 0.0, -center_x],
            [0.0, 1.0, 0.0, 0.0],
            [0.0, 0.0, 1.0, 0.0],
            [0.0, 0.0, 0.0, 1.0],
        ],
        "distortion": [],
    }


def _write_new(path: Path, payload: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("xb") as stream:
        stream.write(payload)
        stream.flush()
        os.fsync(stream.fileno())


def _flush_directory(path: Path) -> None:
    descriptor = os.open(path, os.O_RDONLY)
    try:
        os.fsync(descriptor)
    finally:
        os.close(descriptor)


def create_synthetic_multiview_fixture(
    output: Path,
    *,
    camera_count: int = 3,
    frame_count: int = 3,
    width: int = 32,
    height: int = 24,
) -> dict[str, Any]:
    """Atomically create one deterministic contract fixture.

    The final frame is diagnostic and every earlier frame is train-role.  The
    pixels are generated by integer arithmetic and contain no external media or
    model output. The fixture is released with the project under Apache-2.0.
    """

    camera_count = _positive("camera_count", camera_count, minimum=2)
    frame_count = _positive("frame_count", frame_count, minimum=2)
    width = _positive("width", width, minimum=8)
    height = _positive("height", height, minimum=8)
    if camera_count > 8 or frame_count > 16 or width > 256 or height > 256:
        raise ContractError("synthetic fixture exceeds the bounded smoke-test profile")

    destination = output.expanduser().resolve()
    if os.path.lexists(destination):
        raise OutputExistsError(f"refusing to overwrite synthetic fixture: {destination}")
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = Path(
        tempfile.mkdtemp(prefix=f".{destination.name}.incomplete-", dir=destination.parent)
    )
    try:
        observations: list[dict[str, Any]] = []
        image_records: list[dict[str, Any]] = []
        camera_ids = [f"cam{index:03d}" for index in range(camera_count)]
        for frame_index in range(frame_count):
            role = "diagnostic" if frame_index == frame_count - 1 else "train"
            timestamp = round(frame_index / 30.0, 9)
            for camera_index, camera_id in enumerate(camera_ids):
                relative = Path("images") / camera_id / f"{frame_index:06d}.png"
                payload = _png_bytes(
                    width=width,
                    height=height,
                    camera_index=camera_index,
                    frame_index=frame_index,
                )
                _write_new(temporary / relative, payload)
                digest = hashlib.sha256(payload).hexdigest()
                image_records.append(
                    {"bytes": len(payload), "path": relative.as_posix(), "sha256": digest}
                )
                observations.append(
                    {
                        "observation_id": f"obs_{camera_id}_{frame_index:06d}",
                        "camera_id": camera_id,
                        "frame_id": frame_index,
                        "timestamp_seconds": timestamp,
                        "role": role,
                        "image": {
                            "path": relative.as_posix(),
                            "sha256": digest,
                            "width": width,
                            "height": height,
                            "color_space": "srgb_encoded",
                            "encoding": {
                                "container": "png",
                                "channel_order": "RGB",
                                "bit_depth": 8,
                                "stored_range": "full",
                                "declared_transfer": None,
                                "declared_primaries": None,
                                "declared_matrix": None,
                                "canonical_decode_profile": "srgb_reference_assumption_v1",
                            },
                        },
                        "camera": _camera(
                            camera_index,
                            camera_count=camera_count,
                            width=width,
                            height=height,
                        ),
                    }
                )

        generation = {
            "camera_count": camera_count,
            "frame_count": frame_count,
            "generator": GENERATOR_ID,
            "height": height,
            "images": image_records,
            "width": width,
        }
        manifest: dict[str, Any] = {
            "schema_version": "p2g.observation_manifest.v2",
            "dataset_id": "pixel4dgs_synthetic_multiview_v1",
            "source": {
                "description": (
                    "Deterministic integer-generated RGB contract fixture; no third-party "
                    "media or learned output is included."
                ),
                "license": "Apache-2.0",
                "license_status": "declared",
                "root_sha256": sha256_json(generation),
            },
            "coordinate_conventions": {
                "handedness": "right",
                "extrinsic": "world_to_camera",
                "pixel_center": "half_pixel",
                "time_unit": "seconds",
                "photometric_space": "linear_rgb",
            },
            "sync": {
                "variant": "synthetic_exact_v1",
                "tolerance_seconds": 0.0,
                "per_camera_offset_seconds": dict.fromkeys(camera_ids, 0.0),
            },
            "transforms": [],
            "observations": observations,
        }
        validate_payload("observation", manifest)
        manifest_path = temporary / "observation_manifest.json"
        write_new_json(manifest_path, manifest)

        receipt: dict[str, Any] = {
            "schema_version": FIXTURE_SCHEMA,
            "status": "PASS",
            "generator": GENERATOR_ID,
            "configuration": {
                "camera_count": camera_count,
                "frame_count": frame_count,
                "height": height,
                "train_frame_count": frame_count - 1,
                "width": width,
            },
            "manifest": {
                "bytes": manifest_path.stat().st_size,
                "path": "observation_manifest.json",
                "sha256": hashlib.sha256(manifest_path.read_bytes()).hexdigest(),
            },
            "images": image_records,
            "rights": {
                "contains_third_party_payload": False,
                "license": "Apache-2.0",
                "publication_status": "source_fixture_redistributable",
            },
            "claim_boundary": (
                "This generated fixture checks contracts and pipeline connectivity only; it "
                "does not establish real-scene reconstruction quality or MI300X performance."
            ),
        }
        receipt["logical_sha256"] = sha256_json(receipt)
        write_new_json(temporary / "fixture.json", receipt)
        _flush_directory(temporary)
        if os.path.lexists(destination):
            raise OutputExistsError(
                f"synthetic fixture destination appeared during publication: {destination}"
            )
        os.rename(temporary, destination)
        _flush_directory(destination.parent)
        return receipt
    except BaseException:
        shutil.rmtree(temporary, ignore_errors=True)
        raise


__all__ = [
    "FIXTURE_SCHEMA",
    "GENERATOR_ID",
    "create_synthetic_multiview_fixture",
]
